### ISSUE TITLE
cpymspec has no class isotopePattern (or InstrumentModel)

### ISSUE THREAD

**Issue by andy-d-palmer** [METASPACE2020/sm-analytics-python#3]
Due to recent changes to cpymspec api??

---

ImportError                               Traceback (most recent call last)
<ipython-input-12-820d5f45c04f> in <module>()
----> 1 from sm_annotation_utils import sm_annotation_utils
      2 
      3 config = 'es_MB_config.yml'
      4 remote_instance = sm_annotation_utils.SMInstance(config)
      5 dataset_name = "MBa2s1"

/home/palmer/Documents/python_codebase/engine_annotation_utils/sm_annotation_utils/sm_annotation_utils.py in <module>()
      8 import re
      9 
---> 10 from cpyMSpec import isotopePattern, InstrumentModel
     11 
     12 ISO_IMG_SEL = """select img.peak, img.pixel_inds, img.intensities, ds.img_bounds

ImportError: cannot import name isotopePattern

**Comment by andy-d-palmer** [comment]
Would it would be better if the general api for access es results didn't require spectral processing libraries?

**Comment by lomereiter** [comment]
We've agreed earlier not to store isotope patterns in the database or ES index, so it's necessary for image plotting. I moved the import into the method though.
